# NumPy Basics

In [1]:
import numpy as np

## Creating array

In [2]:
# create one-dimensional array
a = np.array([1, 2, 3])
print(a)
print(f"dimension: {a.ndim}")

[1 2 3]
dimension: 1


In [3]:
# create two-dimensional array
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
print(b)
print(f"dimension: {b.ndim}")

[[1.5 2.  3. ]
 [4.  5.  6. ]]
dimension: 2


In [4]:
# create three-dimensional array
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype=float)
print(c)
print(f"dimension: {c.ndim}")

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
dimension: 3


## Initial Placeholders

In [5]:
# Create an array of zeros
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Create an array of ones
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
# Create an array of evenly spaced values
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
# Create a constant array
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [9]:
# Create a 2x2 identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [10]:
# Create an array with random values
np.random.random((2, 2))

array([[0.34924333, 0.05471826],
       [0.58918897, 0.32075785]])

In [11]:
# Create an empty array
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## Data Types

In [12]:
np.int64
np.float32
np.string_
np.unicode_

numpy.str_

## Inspecting Arrays

In [13]:
# array dimensions
a = np.ones((3,2))
a.shape

(3, 2)

In [14]:
# array length
b = np.ones((5, 7))
len(b)

5

In [15]:
# number of array dimensions
c = np.array([(1, 2, 3), (4, 5, 6)])
c.ndim

2

In [16]:
# number of array elements
d = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
d.size

9

In [17]:
# data type of array elements
e = np.array([1, 2, 3])
e.dtype

dtype('int64')

In [18]:
# name of data type
f = np.array([1, 2, 3], dtype=float)
f.dtype.name

'float64'

In [19]:
# convert an array to a different type
g = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float)
g.astype(int)

array([1, 2, 3, 4, 5])

In [20]:
a = np.arange(15).reshape(3, 5)
print(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


#### count of NAN elements in np array

In [21]:
np.count_nonzero(np.isnan(np.array([np.NAN, 1, 2, np.NAN, 3, 4], dtype=np.float64)))

2

## Array Mathematics

### Arithmetic Operations

In [22]:
a = np.array([5, 4, 3])
b = np.array([4, 3, 2])

# subtraction
a - b
np.subtract(a, b)

# addition
a + b
np.add(a, b)

# division
a / b
np.divide(a, b)

# multiplication
a * b
np.multiply(a, b)

# exponentiation
np.exp(b)

# square root
np.sqrt(b)

# dot product
a.dot(2)

array([10,  8,  6])

### Comparison

In [23]:
# Element-wise comparison
a = np.array([1, 2, 4, 8])
b = np.array([2, 2, 2, 8])
a == b

array([False,  True, False,  True])

In [24]:
# Element-wise comparison
a = np.array([2, 4, 6, 8, 10])
a < 6

array([ True,  True, False, False, False])

In [25]:
# Array-wise comparison
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 4, 5, 6])
np.array_equal(a, b)

False

### Aggregate Functions

In [26]:
# array-wise sum
a = np.array([1, 2, 3, 4, 5])
a.sum()

15

In [27]:
# array-wise minimum value
a = np.array([5, 2, 9, 8, 12])
a.min()

2

In [28]:
# maximum value of an array row
a = np.array([(1, 42, 3), (4, 5, 6), (12, 8, 9)])
a.max(axis=1)

array([42,  6, 12])

In [29]:
# cumulative sum of elements
a = np.array([(1, 42, 3), (4, 5, 6), (12, 8, 9)])
a.cumsum(axis=1)

array([[ 1, 43, 46],
       [ 4,  9, 15],
       [12, 20, 29]])

In [30]:
# mean
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.mean()

5.5

In [31]:
# standard deviation
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.std(a)

2.8722813232690143

### Copying Arrays

In [32]:
# create a view of the array with the same data
a = np.array([1, 3, 4, 2, 5])
b = a.view()
print(b)
a.sort()
print(b)

[1 3 4 2 5]
[1 2 3 4 5]


In [33]:
# create a copy of the array
a = np.array([1, 3, 4, 2, 5])
b = np.copy(a)
print(b)
a.sort()
print(b)

[1 3 4 2 5]
[1 3 4 2 5]


In [34]:
# create a deep copy of the array
a = np.array([1, 3, 4, 2, 5])
b = a.copy()
print(b)
a.sort()
print(b)

[1 3 4 2 5]
[1 3 4 2 5]


### Sorting Arrays

In [35]:
a = np.array([4, 2, 7, 0, 9])
a.sort()
print(a)

[0 2 4 7 9]


In [36]:
a = np.array([(3, 1, 2, 8), (4, 9, 0, 7)])
a.sort()
print(a)

[[1 2 3 8]
 [0 4 7 9]]


In [37]:
a = np.array([(3, 1, 2, 8), (4, 9, 0, 7)])
a.sort(axis=0)
print(a)

[[3 1 0 7]
 [4 9 2 8]]


## Subsetting, Slicing, Indexing

### Subsetting

In [38]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [39]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print(a[1, 2])

[[1 2 3]
 [4 5 6]]
6


### Slicing

In [40]:
# select items at index 0 and 1
a = np.array([1, 2, 3])
print(a[0:2])

[1 2]


In [41]:
# select items at rows 0 and 1 in column 1
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)
print(b[0:2, 1])

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[2. 5.]


In [42]:
# select all items at row 0
c = np.array([(1.5, 2, 3), (4, 5, 6)])
print(c)
print(c[:1])

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5 2.  3. ]]


In [43]:
# reversed array
d = np.array([1, 2, 3, 4, 5])
r = d[: :-1]
print(r)

[5 4 3 2 1]


### Boolean indexing

In [44]:
a = np.array([1, 2, 3, 4, 5])
a[a < 4]

array([1, 2, 3])

### Fancy indexing

In [45]:
a[[0, 4, 0, 3, 0]]

array([1, 5, 1, 4, 1])

## Array Manipulation

### Transposing array

In [46]:
## Transposing array
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
a_transpose = np.transpose(a)
print(a_transpose)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [47]:
## Transposing array
c = np.array([[1, 2, 3],[4, 5, 6]])
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Changing array shape

#### flattening

In [48]:
# flatten the array
a = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
print(a)
print("flattened...")
print(a.ravel())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
flattened...
[1 2 3 4 5 6 7 8 9]


#### reshaping/resizing

In [49]:
# reshape
a = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(a)
print(a.reshape(4, 2))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
# adding/removing elements
a = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
h = np.resize(a, (2, 3))
print(h)


[[1 2 3]
 [4 5 6]]


#### adding/removing elements

In [51]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7])
c = np.append(a, b)
print(c)

[1 2 3 4 5 6 7]


In [52]:
a = np.array([1, 2, 3, 4])
b = np.insert(a, 1, 42)
b

array([ 1, 42,  2,  3,  4])

In [53]:
a = np.array([1, 2, 3, 4, 5])
b = np.delete(a, [1])
print(b)

[1 3 4 5]


#### combining arrays

In [54]:
# concatenate arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b), axis=0)
print(c)

[1 2 3 4 5 6]


In [55]:
# stack arrays vertically
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


In [56]:
# stack arrays horizontally
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(7, 8, 9), (10, 11, 12)])
c = np.hstack((a, b))
print(c)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#### splitting arrays

In [57]:
# split array horizontally at some index
a = np.arange(16).reshape((4, 4))
print(a)
b = np.hsplit(a, 2)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [58]:
# split array vertically at some index
a = np.arange(16).reshape((4, 4))
print(a)
b = np.vsplit(a, 2)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [59]:
# shuffle a 2-D array
s1 = np.arange(0, 20, 1).reshape(5, 4)
np.random.shuffle(s1)
s1

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

## Iterating over numpy arrays

### 1-D array

In [60]:
a = np.arange(0, 5, 1)
for i in a:
    print(i)

0
1
2
3
4


### 2-D array

In [61]:
b = np.arange(0, 10, 1).reshape(2, 5)
for i in np.nditer(b):
    print(i)

0
1
2
3
4
5
6
7
8
9
