In [1]:
import numpy as np
import torch

## Matrices

### Convert numpy array to PyTorch tensor

In [2]:
arr = np.array([[1, 2], [3, 4]])
torch.tensor(arr)

tensor([[1, 2],
        [3, 4]])

### Matrices with default values

In [3]:
torch.zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.ones((3, 2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

### Matrices with random values

In [5]:
torch.rand((3, 4))

tensor([[0.0921, 0.4742, 0.8181, 0.9567],
        [0.8640, 0.5548, 0.3753, 0.7888],
        [0.1254, 0.4404, 0.1967, 0.4793]])

### Numpy to Torch

In [6]:
np_array = np.ones((2, 3))
torch_tensor = torch.from_numpy(np_array)
torch_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
# memory is shared
np_array[1][1] = 2.0
print(np_array)
print(torch_tensor)

[[1. 1. 1.]
 [1. 2. 1.]]
tensor([[1., 1., 1.],
        [1., 2., 1.]], dtype=torch.float64)


In [8]:
np_array_uint8 = np.ones((2, 3), dtype=np.uint8)
torch_tensor_2 = torch.from_numpy(np_array_uint8)
print(torch_tensor_2)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)


### Torch to Numpy

In [9]:
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(torch_tensor)
print(torch_tensor.numpy())

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


### Tensor Resizing

In [10]:
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch_tensor.size()

torch.Size([2, 3])

In [11]:
print(torch_tensor.view(-1, 6))
print(torch_tensor.view(6, -1))

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [12]:
torch_tensor.view(6)

tensor([1, 2, 3, 4, 5, 6])

### Element-wise addition

In [13]:
a = torch.ones((2, 3))
print(a)
b =  a + a
print(b)

# in-place
b.add_(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])


## Gradients

### Tensors with gradients

$$y=5x^4+3x^3+7x^2+9x-5$$
derivative: $$f^{\prime}(x)=20x^3+9x^2+9$$
$$f^{\prime}(2)=20(2)^3+9(2)^2+14(2)+9=233$$

In [14]:
x = torch.tensor([[2., 2.], [2., 2.]], requires_grad=True)

In [15]:
y = 5 * x**4 + 3 * x ** 3 + 7 * x ** 2 + 9 * x -5

In [16]:
# we can only call 'backward' on scalars
sum = torch.sum(y)
print(sum)

tensor(580., grad_fn=<SumBackward0>)


In [17]:
sum.backward()

In [18]:
x.grad

tensor([[233., 233.],
        [233., 233.]])