In [3]:
import numpy as np
import torch

## Matrices

### Convert numpy array to PyTorch tensor

In [4]:
arr = np.array([[1, 2], [3, 4]])
torch.tensor(arr)

tensor([[1, 2],
        [3, 4]])

### Matrices with default values

In [5]:
torch.zeros((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones((3, 2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

### Matrices with random values

In [8]:
torch.rand((3, 4))

tensor([[0.0881, 0.1807, 0.4831, 0.8420],
        [0.2021, 0.2570, 0.4229, 0.9944],
        [0.1833, 0.2924, 0.7403, 0.9573]])

### Numpy to Torch

In [20]:
np_array = np.ones((2, 3))
torch_tensor = torch.from_numpy(np_array)
torch_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
# memory is shared
np_array[1][1] = 2.0
print(np_array)
print(torch_tensor)

[[1. 1. 1.]
 [1. 2. 1.]]
tensor([[1., 1., 1.],
        [1., 2., 1.]], dtype=torch.float64)


In [22]:
np_array_uint8 = np.ones((2, 3), dtype=np.uint8)
torch_tensor_2 = torch.from_numpy(np_array_uint8)
print(torch_tensor_2)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)


### Torch to Numpy

In [23]:
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(torch_tensor)
print(torch_tensor.numpy())

tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


### Tensor Resizing

In [29]:
torch_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch_tensor.size()

torch.Size([2, 3])

In [33]:
print(torch_tensor.view(-1, 6))
print(torch_tensor.view(6, -1))

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [34]:
torch_tensor.view(6)

tensor([1, 2, 3, 4, 5, 6])

### Element-wise addition

In [38]:
a = torch.ones((2, 3))
print(a)
b =  a + a
print(b)

# in-place
b.add_(a)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])


## Gradients

### Tensors with gradients

$$y=5x^4+3x^3+7x^2+9x-5$$
drivative: $$f^{\prime}(x)=20x^3+9x^2+9$$
$$f^{\prime}(2)=20(2)^3+9(2)^2+14(2)+9=233$$

In [90]:
x = torch.tensor([[2., 2.], [2., 2.]], requires_grad=True)

In [91]:
y = 5 * x**4 + 3 * x ** 3 + 7 * x ** 2 + 9 * x -5

In [92]:
# we can only call 'backward' on scalars
sum = torch.sum(y)
print(sum)

tensor(580., grad_fn=<SumBackward0>)


In [93]:
sum.backward()

In [94]:
x.grad

tensor([[233., 233.],
        [233., 233.]])