### Using Open AI's gym, Keras, and Deep Q Learning to Balance A Pole on a Cart

<p>https://keon.io/deep-q-learning/</p>

#### Random Actions

In [1]:
import gym
env = gym.make('CartPole-v0')

for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[-0.03696429  0.03165005  0.01131376  0.00860945]
[-0.03633129 -0.16363232  0.01148595  0.30484042]
[-0.03960393  0.03132408  0.01758276  0.01580191]
[-0.03897745  0.22618952  0.0178988  -0.271282  ]
[-0.03445366  0.0308168   0.01247316  0.02699211]
[-0.03383733  0.22575767  0.013013   -0.26172945]
[-0.02932217  0.42069147  0.00777841 -0.55027968]
[-0.02090834  0.61570331 -0.00322718 -0.84050175]
[-0.00859428  0.81086917 -0.02003722 -1.13419781]
[ 0.00762311  1.00624752 -0.04272117 -1.43309706]
[ 0.02774806  1.20186973 -0.07138312 -1.73881884]
[ 0.05178545  1.39772866 -0.10615949 -2.05282787]
[ 0.07974002  1.20384143 -0.14721605 -1.79478659]
[ 0.10381685  1.01064358 -0.18311178 -1.55124982]
Episode finished after 14 timesteps
[-0.00047566 -0.0117312   0.0039567  -0.02227894]
[-0.00071029 -0.20690967  0.00351112  0.27164974]
[-0.00484848 -0.40208155  0.00894411  0.56543802]
[-0.01289011 -0.59732783  0.02025287  0.86092526]
[-0.02483667 -0.79271965  0.03747138  1.15990682]
[-0.04069106 -

[-0.01335254  0.22243618  0.00118801 -0.24869369]
[-0.00890382  0.02729729 -0.00378587  0.04436373]
[-0.00835787  0.22247332 -0.00289859 -0.24951127]
[-0.00390841  0.02739288 -0.00788882  0.04225597]
[-0.00336055  0.22262706 -0.0070437  -0.25290547]
[ 0.00109199  0.0276064  -0.01210181  0.03754744]
[ 0.00164412  0.22289978 -0.01135086 -0.25892902]
[ 0.00610212  0.0279417  -0.01652944  0.03015218]
[ 0.00666095  0.22329674 -0.0159264  -0.26769979]
[ 0.01112688  0.02840566 -0.02128039  0.01991759]
[ 0.011695   -0.16640474 -0.02088204  0.30581107]
[ 0.0083669  -0.36122299 -0.01476582  0.59183586]
[ 0.00114244 -0.16589747 -0.0029291   0.29453852]
[-0.00217551 -0.36097754  0.00296167  0.58629622]
[-0.00939506 -0.16589719  0.01468759  0.29454771]
[-0.012713   -0.36122543  0.02057855  0.59182646]
[-0.01993751 -0.16639753  0.03241508  0.30569615]
[-0.02326546 -0.36196605  0.038529    0.60842319]
[-0.03050478 -0.55760486  0.05069746  0.91298834]
[-0.04165688 -0.75337465  0.06895723  1.22116439]


[-0.02388482  0.02647345  0.01464087  0.03446862]
[-0.02335535 -0.16885536  0.01533024  0.3317347 ]
[-0.02673246 -0.36419213  0.02196493  0.62921234]
[-0.0340163  -0.55961361  0.03454918  0.92873102]
[-0.04520858 -0.75518451  0.0531238   1.23206775]
[-0.06031227 -0.56078446  0.07776516  0.9564901 ]
[-0.07152796 -0.36678962  0.09689496  0.68921719]
[-0.07886375 -0.56311322  0.1106793   1.01076383]
[-0.09012601 -0.36962827  0.13089458  0.75478554]
[-0.09751858 -0.56628839  0.14599029  1.08562544]
[-0.10884435 -0.76300256  0.1677028   1.42032667]
[-0.1241044  -0.5703052   0.19610933  1.18440954]
Episode finished after 12 timesteps


In [2]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
print(env.observation_space)

Discrete(2)
Box(4,)


In [3]:
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [4]:
from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8

In [5]:
def run_episode(env, parameters, show=False):  
    observation = env.reset()
    totalreward = 0
    for _ in range(200):
        if show:
            env.render()
        action = 0 if np.matmul(parameters,observation) < 0 else 1
        observation, reward, done, info = env.step(action)
        totalreward += reward
        if done:
            break
    return totalreward

In [6]:
import numpy as np
parameters = np.random.rand(4) * 2 - 1  
for i_episode in range(20):
    print(run_episode(env, parameters))

10.0
10.0
9.0
10.0
9.0
10.0
9.0
9.0
10.0
9.0
10.0
10.0
10.0
8.0
9.0
9.0
10.0
9.0
10.0
10.0


### Random Search

In [7]:
bestparams = None  
bestreward = 0  
for _ in range(10000):  
    parameters = np.random.rand(4) * 2 - 1
    reward = run_episode(env,parameters)
    if reward > bestreward:
        bestreward = reward
        bestparams = parameters
        # considered solved if the agent lasts 200 timesteps
        if reward == 200:
            break

In [8]:
bestparams

array([0.02989972, 0.59716591, 0.80630922, 0.77576872])

In [9]:
run_episode(env, bestparams, show=False)

200.0

###  Keras

https://github.com/keon/deep-q-learning

In [11]:
import random
import gym
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

#EPISODES = 1000
EPISODES = 50

class DQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95    # discount rate
        self.epsilon = 1.0  # exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001
        self.model = self._build_model()

    def _build_model(self):
        # Neural Net for Deep-Q learning Model
        model = Sequential()
        model.add(Dense(24, input_dim=self.state_size, activation='relu'))
        model.add(Dense(24, activation='relu'))
        model.add(Dense(self.action_size, activation='linear'))
        model.compile(loss='mse',
                      optimizer=Adam(lr=self.learning_rate))
        return model

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        act_values = self.model.predict(state)
        return np.argmax(act_values[0])  # returns action

    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            #print("state: {}, action: {}, reward: {}, next_state: {}, done: {}".format(state, action, reward, next_state, done))
            if not done:
                target = (reward + self.gamma *
                          np.amax(self.model.predict(next_state)[0]))
            target_f = self.model.predict(state)
            target_f[0][action] = target
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

    def load(self, name):
        self.model.load_weights(name)

    def save(self, name):
        self.model.save_weights(name)


if __name__ == "__main__":
    env = gym.make('CartPole-v1')
    state_size = env.observation_space.shape[0]
    action_size = env.action_space.n
    agent = DQNAgent(state_size, action_size)
    agent.load("./save/cartpole-dqn.h5")
    done = False
    batch_size = 32

    for e in range(EPISODES):
        
        state = env.reset()
        state = np.reshape(state, [1, state_size])
        
        for time in range(500):
            # turn this off if you don't want to render
            env.render()
            
            action = agent.act(state)
            
            next_state, reward, done, _ = env.step(action)
            reward = reward if not done else -10
            next_state = np.reshape(next_state, [1, state_size])
            
            agent.remember(state, action, reward, next_state, done)
            state = next_state
            if done:
                print("episode: {}/{}, score: {}, e: {:.2}".format(e, EPISODES, time, agent.epsilon))
                break
            if len(agent.memory) > batch_size:
                agent.replay(batch_size)
        if e % 10 == 0:
            agent.save("./save/cartpole-dqn.h5")

episode: 0/50, score: 53, e: 0.9
episode: 1/50, score: 12, e: 0.85
episode: 2/50, score: 20, e: 0.77
episode: 3/50, score: 18, e: 0.7
episode: 4/50, score: 56, e: 0.53
episode: 5/50, score: 36, e: 0.44
episode: 6/50, score: 89, e: 0.28
episode: 7/50, score: 140, e: 0.14
episode: 8/50, score: 140, e: 0.069
episode: 9/50, score: 54, e: 0.053
episode: 10/50, score: 10, e: 0.05
episode: 11/50, score: 72, e: 0.035
episode: 12/50, score: 114, e: 0.02
episode: 13/50, score: 120, e: 0.011
episode: 14/50, score: 18, e: 0.01
episode: 15/50, score: 11, e: 0.01
episode: 16/50, score: 107, e: 0.01
episode: 17/50, score: 97, e: 0.01
episode: 18/50, score: 98, e: 0.01
episode: 19/50, score: 79, e: 0.01
episode: 20/50, score: 109, e: 0.01
episode: 21/50, score: 215, e: 0.01
episode: 22/50, score: 116, e: 0.01
episode: 23/50, score: 80, e: 0.01
episode: 24/50, score: 174, e: 0.01
episode: 25/50, score: 79, e: 0.01
episode: 26/50, score: 141, e: 0.01
episode: 27/50, score: 231, e: 0.01
episode: 28/50, s

In [12]:
agent

In [13]:
agent.save("./save/cartpole-dqn.h5")