### Using Open AI's gym, Keras, and Deep Q Learning to Balance A Pole on a Cart

<p>https://keon.io/deep-q-learning/</p>

#### Random Actions

In [1]:
import gym
env = gym.make('CartPole-v0')

for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[-0.01391946 -0.00842033 -0.01275932 -0.03719595]
[-0.01408787 -0.20335701 -0.01350323  0.25143413]
[-0.01815501 -0.00804486 -0.00847455 -0.04547721]
[-0.01831591  0.18719758 -0.0093841  -0.34082184]
[-0.01457195 -0.00778961 -0.01620053 -0.05111283]
[-0.01472775  0.18756085 -0.01722279 -0.34886281]
[-0.01097653  0.38292347 -0.02420005 -0.64692652]
[-0.00331806  0.57837409 -0.03713858 -0.94713074]
[ 0.00824942  0.77397595 -0.05608119 -1.25124744]
[ 0.02372894  0.96976988 -0.08110614 -1.56095583]
[ 0.04312434  1.16576319 -0.11232526 -1.87779844]
[ 0.0664396   1.36191661 -0.14988123 -2.2031286 ]
[ 0.09367793  1.16852055 -0.1939438  -1.96018709]
Episode finished after 13 timesteps
[-0.01636456  0.04756881  0.02306792 -0.03864501]
[-0.01541319  0.2423525   0.02229502 -0.32396145]
[-0.01056614  0.0469203   0.01581579 -0.02433181]
[-0.00962773 -0.14842485  0.01532916  0.27329892]
[-0.01259623 -0.34376213  0.02079514  0.57077702]
[-0.01947147 -0.53916944  0.03221068  0.86993793]
[-0.03025486 -

[ 0.0791066   0.39179254 -0.17491254 -0.88755177]
[ 0.08694245  0.19942077 -0.19266357 -0.65455946]
[ 0.09093086  0.39662886 -0.20575476 -1.00119172]
Episode finished after 23 timesteps
[ 0.02685196  0.02998928 -0.01324981  0.03082762]
[ 0.02745174  0.22529871 -0.01263326 -0.26600614]
[ 0.03195772  0.03035933 -0.01795338  0.02266553]
[ 0.0325649   0.22573408 -0.01750007 -0.27562738]
[ 0.03707959  0.03086613 -0.02301262  0.01148503]
[ 0.03769691  0.22631042 -0.02278291 -0.28836889]
[ 0.04222312  0.03152065 -0.02855029 -0.00295766]
[ 0.04285353  0.22704017 -0.02860945 -0.30451007]
[ 0.04739433  0.03233737 -0.03469965 -0.0209854 ]
[ 0.04804108 -0.16227022 -0.03511935  0.2605506 ]
[ 0.04479568 -0.35687369 -0.02990834  0.54195284]
[ 0.0376582  -0.16134443 -0.01906929  0.23999838]
[ 0.03443131 -0.35618885 -0.01426932  0.52660584]
[ 0.02730754 -0.16086906 -0.0037372   0.22946094]
[ 0.02409016 -0.3559374   0.00085202  0.52096268]
[ 0.01697141 -0.16082746  0.01127127  0.22854836]
[ 0.01375486 -

[-0.0425538  -0.00490739  0.02875598  0.07656149]
[-0.04265195  0.18979078  0.0302872  -0.20691192]
[-0.03885614  0.38446683  0.02614897 -0.48988901]
[-0.0311668   0.57921032  0.01635119 -0.77421746]
[-1.95825941e-02  7.74103562e-01  8.66837146e-04 -1.06171121e+00]
[-0.00410052  0.96921402 -0.02036739 -1.35412194]
[ 0.01528376  1.16458563 -0.04744983 -1.65310616]
[ 0.03857547  1.3602284  -0.08051195 -1.96018502]
[ 0.06578004  1.16604654 -0.11971565 -1.69350072]
[ 0.08910097  0.97249297 -0.15358566 -1.44036075]
[ 0.10855083  0.77955994 -0.18239288 -1.19934463]
[ 0.12414203  0.58720465 -0.20637977 -0.96892444]
Episode finished after 22 timesteps
[ 0.03964333 -0.02415042  0.00246716 -0.04823656]
[ 0.03916032  0.17093606  0.00150243 -0.34014005]
[ 0.04257904 -0.02420723 -0.00530037 -0.04698372]
[ 0.04209489  0.17099032 -0.00624004 -0.34133424]
[ 0.0455147  -0.0240423  -0.01306673 -0.05062557]
[ 0.04503385 -0.21897447 -0.01407924  0.23790622]
[ 0.04065436 -0.02365424 -0.00932111 -0.05918425

In [2]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
print(env.observation_space)

Discrete(2)
Box(4,)


In [3]:
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [4]:
from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8

In [5]:
def run_episode(env, parameters, show=False):  
    observation = env.reset()
    totalreward = 0
    for _ in range(200):
        if show:
            env.render()
        action = 0 if np.matmul(parameters,observation) < 0 else 1
        observation, reward, done, info = env.step(action)
        totalreward += reward
        if done:
            break
    return totalreward

In [6]:
import numpy as np
parameters = np.random.rand(4) * 2 - 1  
for i_episode in range(20):
    print(run_episode(env, parameters))

10.0
10.0
9.0
10.0
9.0
10.0
9.0
9.0
10.0
9.0
10.0
10.0
10.0
8.0
9.0
9.0
10.0
9.0
10.0
10.0


### Random Search

In [7]:
bestparams = None  
bestreward = 0  
for _ in range(10000):  
    parameters = np.random.rand(4) * 2 - 1
    reward = run_episode(env,parameters)
    if reward > bestreward:
        bestreward = reward
        bestparams = parameters
        # considered solved if the agent lasts 200 timesteps
        if reward == 200:
            break

In [8]:
bestparams

array([0.02989972, 0.59716591, 0.80630922, 0.77576872])

In [9]:
run_episode(env, bestparams, show=False)

200.0

###  Keras

https://github.com/keon/deep-q-learning

In [11]:
import random
import gym
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

#EPISODES = 1000
EPISODES = 50

class DQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95    # discount rate
        self.epsilon = 1.0  # exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001
        self.model = self._build_model()

    def _build_model(self):
        # Neural Net for Deep-Q learning Model
        model = Sequential()
        model.add(Dense(24, input_dim=self.state_size, activation='relu'))
        model.add(Dense(24, activation='relu'))
        model.add(Dense(self.action_size, activation='linear'))
        model.compile(loss='mse',
                      optimizer=Adam(lr=self.learning_rate))
        return model

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        act_values = self.model.predict(state)
        return np.argmax(act_values[0])  # returns action

    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            #print("state: {}, action: {}, reward: {}, next_state: {}, done: {}".format(state, action, reward, next_state, done))
            if not done:
                target = (reward + self.gamma *
                          np.amax(self.model.predict(next_state)[0]))
            target_f = self.model.predict(state)
            target_f[0][action] = target
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

    def load(self, name):
        self.model.load_weights(name)

    def save(self, name):
        self.model.save_weights(name)


if __name__ == "__main__":
    env = gym.make('CartPole-v1')
    state_size = env.observation_space.shape[0]
    action_size = env.action_space.n
    agent = DQNAgent(state_size, action_size)
    agent.load("./save/cartpole-dqn.h5")
    done = False
    batch_size = 32

    for e in range(EPISODES):
        
        state = env.reset()
        state = np.reshape(state, [1, state_size])
        
        for time in range(500):
            # turn this off if you don't want to render
            env.render()
            
            action = agent.act(state)
            
            next_state, reward, done, _ = env.step(action)
            reward = reward if not done else -10
            next_state = np.reshape(next_state, [1, state_size])
            
            agent.remember(state, action, reward, next_state, done)
            state = next_state
            if done:
                print("episode: {}/{}, score: {}, e: {:.2}".format(e, EPISODES, time, agent.epsilon))
                break
            if len(agent.memory) > batch_size:
                agent.replay(batch_size)
        if e % 10 == 0:
            agent.save("./save/cartpole-dqn.h5")

episode: 0/50, score: 53, e: 0.9
episode: 1/50, score: 12, e: 0.85
episode: 2/50, score: 20, e: 0.77
episode: 3/50, score: 18, e: 0.7
episode: 4/50, score: 56, e: 0.53
episode: 5/50, score: 36, e: 0.44
episode: 6/50, score: 89, e: 0.28
episode: 7/50, score: 140, e: 0.14
episode: 8/50, score: 140, e: 0.069
episode: 9/50, score: 54, e: 0.053
episode: 10/50, score: 10, e: 0.05
episode: 11/50, score: 72, e: 0.035
episode: 12/50, score: 114, e: 0.02
episode: 13/50, score: 120, e: 0.011
episode: 14/50, score: 18, e: 0.01
episode: 15/50, score: 11, e: 0.01
episode: 16/50, score: 107, e: 0.01
episode: 17/50, score: 97, e: 0.01
episode: 18/50, score: 98, e: 0.01
episode: 19/50, score: 79, e: 0.01
episode: 20/50, score: 109, e: 0.01
episode: 21/50, score: 215, e: 0.01
episode: 22/50, score: 116, e: 0.01
episode: 23/50, score: 80, e: 0.01
episode: 24/50, score: 174, e: 0.01
episode: 25/50, score: 79, e: 0.01
episode: 26/50, score: 141, e: 0.01
episode: 27/50, score: 231, e: 0.01
episode: 28/50, s

In [12]:
agent

In [13]:
agent.save("./save/cartpole-dqn.h5")